const mongoose = require('mongoose');

const roomSchema = new mongoose.Schema(
  {
    room_desc: {
      type: String,
      maxlength: 10000,
    },
    amenities: {
      type: [String],
    },
    status: {
      type: String,
      enum: {
        values: ['Yes', 'NO'],
        message: '{VALUE} is not supported',
      },
      default: 'Yes',
    },
    price: {
      type: Number,
      required: [true, 'Please provide price'],
    },
    type: {
      type: String,
      enum: {
        values: [
          'One-Bedroom Apartment',
          'Two-Bedroom Apartment',
          'Studio Apartment With Creek View',
          'Executive Two-Bedrooms Apartment',
          'Double or Twin Rooms',
          'Triple Rooms',
          'Superior Double',
          'Junior Suites',
          'Classic Double or Twin Rooms',
          'Interconnecting Classic Room',
          'Deluxe Room',
          'Double Deluxe Rooms',
          'Royal Platinum Suites',
          'Standard Room',
          'One-Bedroom Executive',
          'Studio Premier',
          'Executive Suite',
          'Extra Bed / Child',
          'Presidential Suite',
          'Family Room & Twin / Large Superior',
          'Garden View Room',
          'Ocean View Room',
          'Classic Double Room',
          'Classic Single Room',
          'Superior Single View',
          'Superior Park View',
          'Single',
          'Double',
          'Guest Rooms',
          'Accessible Rooms',
          'Suits Room',
          'Business Suites',
          'Heritage Deluxe Room',
          'Suits Room',
          'The Presidental Suits',
          'Club-Shangri-La-Executive Room',
          'Executive',
          'Premium Suits',
          'Deluxe Triple',
          'Deluxe Double/Twin',
          'Heritage Super Deluxe',
          'Heritage Suite Room',
          'Double Bed Delux',
          'Master Room',
          'Superior Queen Room',
          'Family Suite',
          'Deluxe King',
          'Deluxe Single Room',
          'Cottage Deluxe',
          'Premier Room',
          'Club Room',
          'Premier Suite',
          'Gokarna Suite',
          'Corporate Deluxe',
          'Suite',
          'Tent Camp',
          'Deluxe Apartment',
          'Deluxe Twin Room',
          'One Bedroom Apartment',
          'AC Rooms',
          'Deluxe Room With Balcony',
          'Executive Deluxe',
          'Executive Deluxe Single Room',
          'Standard Room With AC',
          'Standard Room Without AC',
          'Lake View Room With AC',
          'Lake View Room Without AC',
          'Normal Room Without AC',
          'Super Deluxe Room',
          'Cottage Room',
        ],
        message: '{VALUE} is not supported',
      },
      default: 'Two-Bedroom Apartment',
    },
    stay: {
      type: String,
      default: '',
    },
    quantity: {
      type: Number,
      default: 1,
    },
    min_stay: {
      type: Number,
      default: 0,
    },
    max_adults: {
      type: Number,
      default: 0,
    },
    min_child: {
      type: Number,
      default: 0,
    },
    no_of_extra_beds: {
      type: Number,
      default: 0,
    },
  },
  {
    timeseries: true,
    timestamps: true,
  }
);

module.exports = mongoose.model('Room', roomSchema);
